name: actions

on:
  push:

jobs:
  test-actions:
    name: test-action
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: run ls
        run: ls
      - name: Hello-world-action
        id: hello-world-action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "James"
      - name: time
        run: echo "'greeting time:' ${{ steps.hello-world-action.outputs.time }}"
      - name: docker action
        uses: docker://hello-world:latest
        
